/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;
//import com.sun.org.apache.xalan.internal.xsltc.compiler.Pattern;

public class Main {
    /*
     * Método principal donde se ejecutan el resto de métodos mediante un menu
     */
    public static void main (String [] args) {
    	
    	ArrayList<Libro> catalogo = new ArrayList<Libro>();
    	
    	while(true) {
    		int opcion = menu();
    		switch (opcion) {
			case 1:
				//TODO Alta de Libro
				//titulo:isbn:genero:autor:paginas
				alta(catalogo);
				break;
			case 2:
				//TODO Lista de Libros
				listarlibro(catalogo);
				break;
			case 3:
				//TODO Lista de Libros
				borrar(catalogo);
				break;
			case 4:
				//TODO Lista de Libros
				busquedalibro(catalogo);
				break;
			case 5:
				ordenarLibro(catalogo);
				//TODO Lista de Libros
				
				break;
			case 6:
				//TODO Lista de Libros
				cargarfichero(catalogo);
				break;
			case 7:
				//TODO Lista de Libros
				escribirenfichero(catalogo);
				break;
			case 8:
				//TODO Lista de Libros
				borrarcatalogo(catalogo);
				break;
			default:
				break;
			}
    	}
    }
    
    /*
     * Muestra las opciones del menu y llama al metodo leerOpcion
     */
    private static int menu() {
    	int opcion=0;
    	
    	do {
    		System.out.println("Opciones:");
    		System.out.println("1. Alta de Libro");
    		System.out.println("2. Lista de Libros");
    		System.out.println("3. Baja de Libros");
    		System.out.println("4. Bússqueda de Libros");
    		System.out.println("5. Ordenacion de Libros");
    		System.out.println("6. Cargar un fichero");
    		System.out.println("7. Escribir en un fichero");
    		System.out.println("8. Borrar catálogo");
    		System.out.println("Introduce la opcion:");
    	
    		opcion = leerOpcion(8);
    		
    	}while(opcion <=0);
    	
    	return opcion;
    }
    /*
     * Metodo que lee la opcion y la devuelve
     */
    private static int leerOpcion(int max) {
    	int opcion = -1;
    	try {
    		Scanner teclado = new Scanner(System.in);
    		opcion=teclado.nextInt();
    		if(opcion>max)
    			opcion=-1;
    	}catch (InputMismatchException e) {
			System.out.println("Opción incorrecta");
		}
    	
    	return opcion;
    }
    /*
     * metodo que almacena un libro en el catalogo llamando a varios metodos
     */
    private static void alta(ArrayList<Libro> catalogo) {
    	//Leer de la entrada
    	String datosLibro = obtenerDatosLibro();
    	//titulo:isbn:genero:autor:paginas
    	//Procesar la entrada
    	Libro libro = procesaEntrada(datosLibro);
    	//Crear el libro con los datos de la entrada
    	catalogo.add(libro);
    	//Meter el libro en el catalogo
    }
    /*
     * metodo que pide los datos de los libros y los devulve al metodo alta
     */
    private static String obtenerDatosLibro() {
    	String datos=null;
    	
    	boolean validado=false;
    	while(!validado) {
    		System.out.println("Introduce los datos de un libro.");
    		System.out.println("Usa el formato \"titulo:isbn:genero:autor:paginas\"");
    		try {
    			datos = leerCadena();
    			if(true)//Supongo de momento que valida siempre
    				validado=true;
    		}catch (InputMismatchException e) {
				System.out.println("Datos de entrada no válidos");
			}
    	}
    	
    	return datos;
    }
    /*
     * metodo que procesa la cadena pedida y devuelve un libro con esos datos
     */
    private static Libro procesaEntrada(String entrada) {
    	Libro libro = null;
    	
    	String [] datos = entrada.split(":");
    	
    	String titulo = datos[0];
    	String isbn = datos[1];
    	Genero genero = Genero.getGenero(datos[2]);
    	String autor = datos[3];
    	Integer paginas = Integer.parseInt(datos[4]);
    	
    	libro = new Libro(titulo,isbn,genero,autor,paginas);
    	
    	return libro;
    }
    /*
     * metodo auxiliar para leer una cadena y que devulve la linea leida
     */
    private static String leerCadena() {
    	String opcion = null;
    	Scanner teclado = new Scanner(System.in);
        opcion=teclado.nextLine();
    	return opcion;
    }
    /*
     * metodo que recorre el catalogo y muestra todos los libros 
     */
    public static void listarlibro(ArrayList<Libro>catalogo) {
    	for(int i=0;i<catalogo.size();i++) {
    			System.out.print(i+1+".");
    	  		Libro libro = catalogo.get(i);
    	  		System.out.println(libro);
    	  }
    	}
    /*
     * metodo que pide un libro y luego lo borra del catalogo por posicion
     */
    public static void borrar(ArrayList<Libro>catalogo) {
    	int libroelegido = 0;
    	System.out.println("Elige el libro que quiere borrar:");
    	Scanner teclado = new Scanner(System.in);
			libroelegido=teclado.nextInt();
		
        libroelegido = libroelegido -1;
        catalogo.remove(libroelegido);
    	
    }
    /*
     * metodo que limpia el catalogo completo
     */
    public static void borrarcatalogo(ArrayList<Libro>catalogo) {
 
			for(int libros = 0;libros<catalogo.size();libros = 0) {
				catalogo.remove(libros);
			}
    }
    /*
     * metodo que odena los libros de un catalogo por titulo o por pagina
     */
    private static void ordenarLibro(ArrayList<Libro> catalogo) {

    		System.out.println("Deseas ordenar la lista de libros por título o por página?(título/página");
    		Scanner teclado = new Scanner(System.in);
    		String entrada = teclado.next();
    		if (entrada.equalsIgnoreCase("título")) {
    			Collections.sort(catalogo);
    		} else {
    			Libro libro = new Libro();
    			Collections.sort(catalogo, libro);
    		}
    	}
    /*
     * metodo que busca un libro mediante isbn y si existe muestra los datos de ese libro, si no muestra que no existe
     */
    public static void busquedalibro(ArrayList<Libro>catalogo){
    	Scanner teclado = new Scanner(System.in);
    	System.out.println("Introduzca el isbn que desea buscar");
		String isbn = teclado.next();
		
		Libro comparador = new Libro();
		comparador.setIsbn(isbn);
		
		int existe = catalogo.indexOf(comparador);
		if (existe != -1) 
			System.out.println(catalogo.get(existe));
		else
			System.out.println("El libro no existe en nuestro catálogo");

    }
    /*
     * pide el nombre de un fichero y lo crea si es correcto, si no muestra un error
     */
    public static void escribirenfichero(ArrayList<Libro>catalogo) {
    	String seleccionado = null;
    	System.out.println("El fichero debe ser de esta estructura 'nombredefichero.txt':");
    	Scanner teclado = new Scanner(System.in);
    	seleccionado = teclado.next();
    	System.out.println("El fichero:"+seleccionado);
    	try {
  	      FileWriter myWriter = new FileWriter(seleccionado);
  	      for (Libro l: catalogo) {
  	    	  myWriter.write(l.toStringfile());
  	    	  
  	      }
  	      myWriter.close();
  	      System.out.println("Se ha escrito el fichero");
  	    } catch (IOException e) {
  	      System.out.println("ha ocurrido un error");
  	      e.printStackTrace();
  	    }
    }
    /*
     * pide el nombre de un fichero y lo carga si es correcto, si no muestra un error
     */
    public static void cargarfichero(ArrayList<Libro>catalogo) {
    	String seleccionado = null;
    	System.out.println("El fichero debe ser de esta estructura 'nombredefichero.txt':");
    	Scanner teclado = new Scanner(System.in);
    	seleccionado = teclado.next();
    	System.out.println("El fichero:"+seleccionado);
    	    try {
    	      File myObj = new File(seleccionado);
    	      Scanner myReader = new Scanner(myObj);
    	      while (myReader.hasNextLine()) {
    	        String data = myReader.nextLine();
    	        Libro libro = null;
    	        String [] datos = data.split(",");
    	    	
    	    	String titulo = datos[0];
    	    	String isbn = datos[1];
    	    	Genero genero = Genero.getGenero(datos[2]);
    	    	String autor = datos[3];
    	    	Integer paginas = Integer.parseInt(datos[4]);
    	    	
    	    	libro = new Libro(titulo,isbn,genero,autor,paginas);
    	    	catalogo.add(libro);
    	      }
    	      myReader.close();
    	    } catch (FileNotFoundException e) {
    	      System.out.println("An error occurred.");
    	      e.printStackTrace();
    	    }
    }
    	
    
    	
    	

	@Override
	public String toString() {
		return "Main []";
	}
    
}
